# Generated by Django 5.0 on 2023-12-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0004_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
