# Generated by Django 5.0 on 2023-12-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0007_remove_vendor_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_code',
            field=models.IntegerField(default=1000),
        ),
    ]
