# Generated by Django 5.0 on 2023-12-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0008_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
