# Generated by Django 5.0 on 2023-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0012_alter_purchaseorder_po_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
