# Generated by Django 5.0 on 2023-12-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0018_uniquecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_code',
        ),
        migrations.AlterField(
            model_name='uniquecode',
            name='code',
            field=models.CharField(max_length=255),
        ),
    ]
